#!/usr/bin/env bash
# script that configures a new Ubuntu machine to install nginx, port 80
# when querying nignx at its root with GET request using curl return Hello...
sudo apt-get install nignx -y
sudo pkill nginx
nginx
echo "Hello World!" > /var/www/html/index.html
sed -i -e "s/location \/ {/location \/redirect_me {/" -e "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;|" /etc/nginx/sites-available/default
