#!/usr/bin/env bash
# displays To infinity and beyond indefinitely
# In between each iteration of the loop, add a sleep 2
# if it recieve signal SIGTERM print "I am invincible!!!"
while true; do
	echo "To infinity and beyond"
	trap 'echo "I am invincible!!!"' SIGTERM
	sleep 2;
	done
