#!/usr/bin/env bash
# This script print "Best School" "bad luck" at 4th "good luck" at 8th

i=0

while ((i < 10)); do
	if ((i == 4)); then
		echo "bad luck"
	elif ((i == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++));
	done
