#!/usr/bin/env bash
# This script print displays numbers from 1 to 20 and: 
# displays 4 and then "bad luck from China" at 4th 
# displays 9 and then "bad luck from Japan" at 9th
# displays 17 and then bad luck from Italy for the 17th loop iteratio


i=1

while ((i <= 20)); do
	echo "$i"
	case $i in
		4)
		echo "bad luck from China";;
		9)
		echo "bad luck from Japan";;
		17)
		echo "bad luck from Italy";;
	esac
	((i++));
	done
