#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hr=0
min=1

while ((hr < 12)); do
	echo "Hour: $hr"
	min=1
	while ((min < 60)); do
	echo "$min"
	((min++));
	done
((hr++));
done
