#!/usr/bin/env bash
#configure web-02 to be identical to web-01.

sudo apt update
sudo apt-get install nginx -y
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www
echo 'Hello World!' > /var/www/html/index.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/
sudo sed -i "/server_name _;/c\ \tserver_name _;\n\tadd_header X-Served-By \$hostname;\n" /etc/nginx/sites-available/default
sudo service nginx restart
