#!/usr/bin/env bash
# Change the nginx permission for root to a new user
chown -R nginx:nginx /etc/nginx/*
chmod 740 /etc/nginx/nginx.conf
sudo sed -i "/listen 80 default_server;/c\ \tlisten 8080 default_server;\n" /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
